name: Shell Script Creation

on:
  push:
    branches:
      - main

jobs:
  create-file:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Create script
        run: |
          cp nextcloud-installer nextcloud-installer.sh
          chmod +x nextcloud-installer.sh

      - name: Commit file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add nextcloud-installer.sh
          git commit -m "Création automatique du script" || exit 0
          git push